# NB: don't set `language: haskell` here
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/racket

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1 RACKET_VERSION=6.1
      compiler: ": #GHC 7.10.1"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,alex-3.1.4,happy-1.19.5,libblas-dev,liblapack-dev], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 RACKET_VERSION=6.1
      compiler: ": #GHC 7.10.2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5,libblas-dev,liblapack-dev], sources: [hvr-ghc]}}

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - unset CC
 - export HAPPYVER=1.19.5
 - export ALEXVER=3.1.4
 - export RACKET_DIR=$HOME/racket/$RACKET_VERSION
 - export PATH=$HOME/bin:$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$RACKET_DIR/bin:$PATH
 - mkdir -p $HOME/bin
 # install Racket if it isn't already installed
 - if [ ! -d $RACKET_DIR ]; then
     git clone https://github.com/greghendershott/travis-racket.git;
     cat travis-racket/install-racket.sh | bash;
   fi

install:
 # install herbie-exec
 - raco exe -o $HOME/bin/herbie-exec herbie/herbie/interface/inout.rkt

 # manually download the expression database
 - wget https://github.com/mikeizbicki/HerbiePlugin/raw/master/data/Herbie.db
 - mkdir -p $HOME/.cabal/share/x86_64-linux-ghc-$GHCVER/HerbiePlugin-0.1.0.0/
 - cp Herbie.db $HOME/.cabal/share/x86_64-linux-ghc-$GHCVER/HerbiePlugin-0.1.0.0/

 # display versions
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

 # install HerbiePlugin
 - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ]; then
     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
   fi
 - travis_retry cabal update
 - "sed -i  's/^jobs:.*$/jobs: 2/' $HOME/.cabal/config"
 - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
 - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt

# check whether current requested install-plan matches cached package-db snapshot
 - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt; then
     echo "cabal build-cache HIT";
     rm -rfv .ghc;
     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
   else
     echo "cabal build-cache MISS";
     rm -rf $HOME/.cabsnap;
     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
     cabal install --only-dependencies --enable-tests --enable-benchmarks;
   fi

# snapshot package-db on cache miss
 - if [ ! -d $HOME/.cabsnap ]; then
     echo "snapshotting package-db to build-cache";
     mkdir $HOME/.cabsnap;
     cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
     cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
   fi

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
